#!/usr/bin/env python3
"""
Regenerate agent skills from their external references using pi + llama.cpp.

Scans .agents/skills/*/SKILL.md, extracts external_references from YAML frontmatter,
spawns up to 3 parallel pi subprocesses (each on a unique provider), and writes
each fully-generated skill into generated_skills.json atomically.

Only skills present in generated_skills.json are considered fully generated —
supports resume on re-run.
"""

import json
import multiprocessing
import multiprocessing.managers
import os
import shutil
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from subprocess import PIPE, Popen, TimeoutExpired

import yaml

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SKILLS_DIR = Path(__file__).parent / ".agents" / "skills"
OUTPUT_JSON = Path(__file__).parent / "generated_skills.json"

PROVIDERS = ["llama.cpp s0", "llama.cpp s1", "llama.cpp s2", "llama.cpp s3"]
MODEL = "Qwen/Qwen3.6-27B"
MAX_CONCURRENT = 3
TIMEOUT_PER_SKILL = 60 * 60  # seconds

SKIP_SKILLS = {"skill", "plan", "git", "tzip"}

# ---------------------------------------------------------------------------
# Retry configuration
# ---------------------------------------------------------------------------
#
# Exponential backoff for LLM call failures:
#   5s → 10s → 20s → 40s → 80s → 160s → 320s → 640s → 900s(cap)
#   → reset to 5s → repeat indefinitely until servers come back.
# ---------------------------------------------------------------------------

RETRY_INITIAL_DELAY = 5        # seconds between first two attempts
RETRY_MAX_DELAY = 900          # 15 minutes — cap before resetting
RETRY_BACKOFF_FACTOR = 2       # exponential multiplier

# ---------------------------------------------------------------------------
# YAML frontmatter parser
# ---------------------------------------------------------------------------


def parse_frontmatter(skill_md_path: Path) -> dict | None:
    """Return the YAML header dict from a SKILL.md, or None on failure."""
    text = skill_md_path.read_text(encoding="utf-8")
    parts = text.split("---", 2)
    if len(parts) < 2:
        return None
    try:
        return yaml.safe_load(parts[1])
    except yaml.YAMLError:
        return None


def prepare_for_regeneration(skill_dir: Path) -> str | None:
    """
    For uncovered skills: preserve YAML header, delete body and reference files.
    Returns the reconstructed header text (with --- delimiters) or None on failure.
    """
    skill_md = skill_dir / "SKILL.md"
    meta = parse_frontmatter(skill_md)
    if meta is None:
        return None

    # Reconstruct YAML header with --- delimiters
    header_text = "---\n" + yaml.dump(meta, default_flow_style=False, sort_keys=False) + "---\n"

    # Write SKILL.md with only the header (body will be regenerated by pi)
    skill_md.write_text(header_text, encoding="utf-8")

    # Delete reference/ directory if it exists
    ref_dir = skill_dir / "reference"
    if ref_dir.exists():
        shutil.rmtree(ref_dir)

    return header_text


# ---------------------------------------------------------------------------
# Skill discovery
# ---------------------------------------------------------------------------


def discover_skills(existing: dict) -> tuple[list[dict], list[dict]]:
    """
    Scan all SKILL.md files and classify into two lists:
      pending — skills with external_references, not in existing (need generation)
       
    Each dict has:
      { "name": str, "refs": [str], "path": str, "mode": str }
    where mode is "regen" if the skill dir exists on disk but wasn't fully
    generated (not in JSON), meaning we preserve the YAML header and clean
    old body/reference files before regenerating.
    """
    pending = []
    for entry in sorted(SKILLS_DIR.iterdir()):
        if not entry.is_dir():
            continue
        name = entry.name
        if name in SKIP_SKILLS:
            continue
        skill_md = entry / "SKILL.md"
        if not skill_md.exists():
            continue
        meta = parse_frontmatter(skill_md)
        if meta is None:
            print(f"[WARN]  Skipping {name} — cannot parse frontmatter")
            continue
        refs = meta.get("external_references", [])
        if not refs:
            print(f"[SKIP]  {name} — no external_references")
            continue
        if name in existing:
            continue
        pending.append({"name": name, "refs": refs, "path": str(skill_md),
                        "mode": "regen"})
    return pending


# ---------------------------------------------------------------------------
# Load / save JSON
# ---------------------------------------------------------------------------


def load_existing() -> dict:
    if OUTPUT_JSON.exists():
        try:
            return json.loads(OUTPUT_JSON.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def save_skill(name: str, content: str, provider: str,
               started_at: str, ended_at: str, duration_seconds: float) -> None:
    """Append one skill to generated_skills.json atomically."""
    tmp = OUTPUT_JSON.with_suffix(".json.tmp")
    data = load_existing()
    data[name] = {
        "skill_md": content,
        "provider": provider,
        "started_at": started_at,
        "ended_at": ended_at,
        "duration_seconds": round(duration_seconds, 2),
    }
    tmp.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.rename(OUTPUT_JSON)  # atomic on POSIX


# ---------------------------------------------------------------------------
# Shared provider queue (managed by a server process)
# ---------------------------------------------------------------------------
#
# We need a thread/process-safe way for workers to "check out" a provider
# and "check it back in" when done, guaranteeing no two workers hold the
# same provider simultaneously.  A multiprocessing.Manager().Queue works
# across forked processes.
#
# Protocol:
#   - On start, the manager pushes all available providers into the queue.
#   - Worker calls q.get() to acquire one (blocks until available).
#   - When done, worker calls q.put(provider) to release it.
# ---------------------------------------------------------------------------


def _build_provider_queue(manager_class):
    """Return a Queue pre-filled with PROVIDERS."""
    q = manager_class.Queue()
    for p in PROVIDERS:
        q.put(p)
    return q


# ---------------------------------------------------------------------------
# Retry wrapper for pi subprocess calls
# ---------------------------------------------------------------------------
#
# Exponential backoff: 5s → 10s → 20s → … → cap at 900s → reset to 5s.
# Loops indefinitely until the provider responds successfully.
# ---------------------------------------------------------------------------


def _pi_call_with_retry(provider: str, prompt: str, name: str, idx: int):
    """
    Call pi subprocess with exponential backoff retry loop.

    Returns (stdout, stderr, returncode, total_duration) on success.
    Never returns on failure — loops until servers come back.
    """
    delay = RETRY_INITIAL_DELAY
    attempt = 0
    total_time = 0.0

    while True:
        attempt += 1
        print(f"[{idx}] Attempt {attempt} for {name} (provider: {provider})", flush=True)

        t0 = time.time()
        try:
            proc = Popen(
                ["pi", "--provider", provider, "--model", MODEL, "-p", prompt],
                stdout=PIPE,
                stderr=PIPE,
                text=True,
            )
            stdout, stderr = proc.communicate(timeout=TIMEOUT_PER_SKILL)
            elapsed = time.time() - t0
            total_time += elapsed

            if proc.returncode == 0 and (stdout or "").strip():
                print(
                    f"[{idx}] SUCCESS on attempt {attempt} "
                    f"({elapsed:.0f}s, total {total_time:.0f}s)",
                    flush=True,
                )
                return stdout, stderr, proc.returncode, total_time

            err_preview = (stderr or "")[:200]
            print(
                f"[{idx}] FAILED attempt {attempt} for {name} "
                f"(rc={proc.returncode}, {elapsed:.0f}s)\n"
                f"      stderr: {err_preview}",
                flush=True,
            )

        except TimeoutExpired:
            proc.kill()
            elapsed = time.time() - t0
            total_time += elapsed
            print(
                f"[{idx}] TIMEOUT on attempt {attempt} after {elapsed:.0f}s",
                flush=True,
            )
        except Exception as exc:
            elapsed = time.time() - t0
            total_time += elapsed
            print(f"[{idx}] ERROR on attempt {attempt}: {exc}", flush=True)

        # Exponential backoff with cap-and-reset
        print(f"[{idx}] Sleeping {delay:.0f}s before retry...", flush=True)
        time.sleep(delay)
        delay *= RETRY_BACKOFF_FACTOR
        if delay > RETRY_MAX_DELAY:
            delay = RETRY_INITIAL_DELAY  # reset to 5s after hitting cap


def generate_skill(args: tuple) -> dict:
    """
    args = (index, skill_dict, provider_queue)
    Returns a status dict for logging.

    provider_queue is a shared Queue — get() blocks until a free provider
    is available, put() returns it after the pi call finishes.

    For "regen" mode skills: preserves YAML header, cleans old body/refs,
    then regenerates fresh.  Uses exponential backoff retry for LLM failures.
    """
    idx, skill, prov_queue = args
    name = skill["name"]
    refs = skill["refs"]
    mode = skill.get("mode", "regen")
    refs_str = ", ".join(refs)

    if mode == "regen":
        prompt = (
            f"/skill:skill '{name}' based on external references {refs_str} . "
            f"This skill has an existing YAML header that was preserved. "
            f"Regenerate the SKILL.md body (after the --- delimiter) and create "
            f"reference files as needed. After reviewing external references, "
            f"write skill until it is complete. Don't ask user any questions. "
            f"Assume the best answers. Proceed!"
        )
    else:
        prompt = (
            f"/skill:skill '{name}' based on external references {refs_str} . "
            f"After reviewing external references, write skill until it is complete. "
            f"Don't ask user any questions. Assume the best answers. Proceed!"
        )

    # Double-check: skip if another run already finished this skill
    if name in load_existing():
        print(f"[{idx}] SKIP   {name} — already in {OUTPUT_JSON.name}", flush=True)
        return {"name": name, "ok": True, "skipped": True}

    # For regen mode: preserve header, clean old body + reference files
    if mode == "regen":
        skill_dir = Path(skill["path"]).parent
        header = prepare_for_regeneration(skill_dir)
        if header:
            print(f"[{idx}] [REGEN] Preserved header, cleaned body/refs for {name}", flush=True)
        else:
            print(f"[{idx}] [REGEN] Could not parse header for {name}, proceeding anyway", flush=True)

    # Print reference URLs used for this skill
    mode_label = "[REGEN]" if mode == "regen" else ""
    print(f"[{idx}] Starting {mode_label} {name} via provider (acquiring...)", flush=True)
    for url in refs:
        print(f"  ref: {url}", flush=True)

    # Acquire a unique provider (blocks if all are in use)
    provider = prov_queue.get()
    print(f"[{idx}] Using provider: {provider}", flush=True)

    started_dt = datetime.now(timezone.utc)
    started_at = started_dt.isoformat()

    try:
        # Retry loop — blocks until success
        stdout, stderr, returncode, duration = _pi_call_with_retry(
            provider, prompt, name, idx
        )

        ended_dt = datetime.now(timezone.utc)
        ended_at = ended_dt.isoformat()

        content = stdout.strip()

        # Persist immediately — skill is fully generated only when in JSON.
        save_skill(name, content, provider, started_at, ended_at, duration)
        print(
            f"[{idx}] DONE   {name} ({len(content):,} chars, {duration:.0f}s total)",
            flush=True,
        )
        return {"name": name, "ok": True, "chars": len(content),
                "elapsed": round(duration, 2)}

    except Exception as exc:
        ended_dt = datetime.now(timezone.utc)
        ended_at = ended_dt.isoformat()
        print(f"[{idx}] UNRECOVERABLE ERROR  {name}: {exc}", flush=True)
        return {"name": name, "ok": False, "error": str(exc)}

    finally:
        # Always release the provider back to the pool
        prov_queue.put(provider)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    print("=" * 70)
    print("Skill Generator — pi + llama.cpp")
    print("=" * 70)

    # Load already-generated for resume
    existing = load_existing()
    if existing:
        print(f"\nResuming — {len(existing)} skill(s) already in {OUTPUT_JSON.name}")

    # Discover skills (returns only those not yet in generated_skills.json)
    pending = discover_skills(existing)
    if not pending:
        print("All skills already generated. Nothing to do.")
        sys.exit(0)

    regen_count = sum(1 for s in pending if s["mode"] == "regen")
    print(f"\nFound {len(pending)} skill(s) to generate ({regen_count} need regeneration)")
    print(f"Providers: {PROVIDERS}")
    print(f"Max concurrent: {MAX_CONCURRENT}")
    print(f"Retry: exponential backoff {RETRY_INITIAL_DELAY}s → {RETRY_MAX_DELAY}s cap, then reset")
    print()

    # Build tasks with shared provider queue
    manager = multiprocessing.Manager()
    prov_queue = _build_provider_queue(manager)

    tasks = [(i, skill, prov_queue) for i, skill in enumerate(pending)]

    # Run with Pool(MAX_CONCURRENT) — exactly 3 concurrent pi processes.
    # The provider Queue ensures no two workers ever hold the same provider
    # at the same time (4 providers, 3 slots → at most 3 in flight).
    results = []
    with multiprocessing.Pool(processes=MAX_CONCURRENT) as pool:
        for result in pool.imap_unordered(generate_skill, tasks):
            results.append(result)

    # Summary
    ok = sum(1 for r in results if r["ok"])
    fail = len(results) - ok
    print("\n" + "=" * 70)
    print(f"Complete: {ok} succeeded, {fail} failed out of {len(results)}")
    print(f"Output   : {OUTPUT_JSON}")
    print("=" * 70)

    if fail:
        print("\nFailed skills:")
        for r in results:
            if not r["ok"]:
                print(f"  - {r['name']}: {r.get('error', 'unknown')}")
        sys.exit(1)


if __name__ == "__main__":
    main()
